In [1]:
import sys
sys.path.append('..')
import numpy as np

In [2]:
from layers import MatMul
from preprocess import preprocess, create_contexts_target, convert_one_hot

In [3]:
text = 'You say goodbye and I say hello .' # . 이거 처리 어떻게 하더라?

In [4]:
corpus, word_to_id, id_to_word = preprocess(text)

In [5]:
corpus

[0, 1, 2, 3, 4, 1, 5, 6]

In [6]:
# corpus로부터 맥락과 타깃을 만들자
contexts, target = create_contexts_target(corpus)

In [7]:
target

array([1, 2, 3, 4, 1, 5])

In [8]:
vocab_size=len(word_to_id)
target=convert_one_hot(target, vocab_size)
contexts=convert_one_hot(contexts, vocab_size)

1
[0. 1. 0. 0. 0. 0. 0.]
2
[0. 0. 1. 0. 0. 0. 0.]
3
[0. 0. 0. 1. 0. 0. 0.]
4
[0. 0. 0. 0. 1. 0. 0.]
1
[0. 1. 0. 0. 0. 0. 0.]
5
[0. 0. 0. 0. 0. 1. 0.]
[0 2]
[1 3]
[2 4]
[3 1]
[4 5]
[1 6]


In [9]:
target

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [10]:
contexts

array([[[1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.]]])

In [11]:
c0 = np.array([1,0,0,0,0,0,0])
c1 = np.array([0,0,1,0,0,0,0])

In [12]:
W_in = np.random.randn(7,3)
W_out = np.random.randn(3,7)

In [13]:
in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

In [14]:
h0 = in_layer0.forward(c0)
h1 = in_layer1.forward(c1)
h = 0.5 * (h0 + h1)
s = out_layer.forward(h)

In [15]:
print(s)

[ 0.83204457  0.69992882 -0.62437999  2.96415301 -2.56158139  1.87515817
  0.57864564]
